<template>
  <div class="loadingio-spinner-wedges-54egs4nfmrq">
    <div class="ldio-lftvexqbp8f">
      <div>
        <div><div></div></div>
        <div><div></div></div>
        <div><div></div></div>
        <div><div></div></div>
      </div>
    </div>
  </div>
</template>

<script>
export default {}
</script>

<style type="text/css">
@keyframes ldio-lftvexqbp8f {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-lftvexqbp8f div {
  box-sizing: content-box;
}

.ldio-lftvexqbp8f > div > div {
  transform-origin: 102.49999999999999px 102.49999999999999px;
  animation: ldio-lftvexqbp8f 7.692307692307692s linear infinite;
  opacity: 0.89;
}
.ldio-lftvexqbp8f > div > div > div {
  position: absolute;
  left: 26.65px;
  top: 26.65px;
  width: 75.85px;
  height: 75.85px;
  border-radius: 75.85px 0 0 0;
  transform-origin: 102.49999999999999px 102.49999999999999px;
}

.ldio-lftvexqbp8f > div div:nth-child(1) {
  animation-duration: 1.923076923076923s;
}

.ldio-lftvexqbp8f > div div:nth-child(2) {
  animation-duration: 2.564102564102564s;
}

.ldio-lftvexqbp8f > div div:nth-child(3) {
  animation-duration: 3.846153846153846s;
}

.ldio-lftvexqbp8f > div div:nth-child(4) {
  animation-duration: 7.692307692307692s;
}

.ldio-lftvexqbp8f > div div:nth-child(1) > div {
  background: #ea3f34;
  transform: rotate(0deg);
}

.ldio-lftvexqbp8f > div div:nth-child(2) > div {
  background: #f2982c;
  transform: rotate(0deg);
}

.ldio-lftvexqbp8f > div div:nth-child(3) > div {
  background: #52a360;
  transform: rotate(0deg);
}

.ldio-lftvexqbp8f > div div:nth-child(4) > div {
  background: #674794;
  transform: rotate(0deg);
}

.ldio-lftvexqbp8f {
  width: 200px;
  height: 200px;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */

  /* transform: translate(0) scale(1); */
}

.loadingio-spinner-wedges-54egs4nfmrq {
  width: 100%;
  height: 100%;
  display: inline-block;
  overflow: hidden;
  position: fixed;
  background-color: none;
  z-index: 10;
}

/* generated by https://loading.io/ */
</style>
